#page title
page_title: Trnslt.me — личный переводчик в вашем смартфоне # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1478569270 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  /assets/press_kit.pdf # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: /assets/appicon.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Trnslt.me # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Личный переводчик в вашем смартфоне. # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Профессиональный голосовой перевод в любое время дня и ночи. Вам больше не надо заранее искать переводчика, договариваться о времени, платить сверхурочно за срочность или работу в ночные часы.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Lingo Team
your_link: https://trnslt.me
your_city: Moscow
email_address: at@trnslt.me
facebook_username:
instagram_username: trnslt
twitter_username: trnslt
github_username: trnslt
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Удалённое общение — перевод телефонного звонка
    description: Приложение подключает к разговору с иностранцем переводчика посредством 3-хсторонней конференц-связи. Вы всего лишь выбираете нужный контакт в записной книжке телефона и язык, на котором говорит собеседник.
    fontawesome_icon_name: phone-alt

  - title: Когда собеседник рядом — перевод на громкой связи
    description: Чтобы начать общение, вам достаточно выбирть язык собеседника, который находится рядом и после подключения удаленного перевдчика перевести телефон на громкую связь и начать общение с иностранцем.
    fontawesome_icon_name: volume-up

  - title: Удобный способ оплаты
    description: По окончании разговора система автоматически списывает необходимую сумму с привязанной банковской карты. Тарификация учитывается посекундно.
    fontawesome_icon_name: credit-card

  - title: Оплата только за фактическое время перевода
    description: Теперь только вы решаете на какое время вам нужен переводчик — если вы пообщались с собеседником 7 минут и 20 секунд, вы заплатите ровно за 7 минут и 20 секунд и ни копейкой больше.
    fontawesome_icon_name: stopwatch-20

  - title: В любое время и в любом месте где есть интернет
    description: Вам понадобился переводчик в нерабочее время или в регионе, где нет нужных переводчиков? В Lingo переводчики доступны 24/7 и в любом месте, где есть Интернет.
    fontawesome_icon_name: globe-europe

  - title: Конфиденциальность превыше всего
    description: Разговоры для переводчика всегда анонимны — ваш телефонный номер и номер вашего собеседника всегда скрыты от переводчика и не могут быть разглашены третьим лицам.
    fontawesome_icon_name: shield-alt

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.0
topbar_title_color: "#ffffff"

cover_image: /assets/headerimage.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "#000000"
cover_overlay_transparency: 0.45

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#000000"

link_color: "#00B956"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#ffffff"
feature_text_color: "#666666"

feature_icons_foreground_color: "#000000"
feature_icons_background_color: "#00B956"

social_icons_foreground_color: "#000000"
social_icons_background_color: "#00B956"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/
# Markdown rendering
markdown: kramdown
lsi: false
safe: true
source: https://github.com/LingoPlatform/lingoplatform.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
